device: 0
RegisteredFetaDataset: 
  data_dir: '../dataset/registered'
  test_set: [1, 6, 10, 24, 30, 36, 43, 44, 50, 53, 62, 73]
AtlasDataset: 
  data_dir: '../dataset/CRL_Fetal_Brain_Atlas_2017v3'
  test_set: []
bias_size: [3, 5]
bias_sigma: [0, 0.1]
gamma: [0.8, 1.2]
